steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pitch-perfect-frontend:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pitch-perfect-frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pitch-perfect-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pitch-perfect-frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--port'
      - '7860'
      - '--set-env-vars'
      - 'BACKEND_API_URL=https://pitch-perfect-backend-792590041292.europe-west1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/pitch-perfect-frontend:$COMMIT_SHA'