name: CD - Deploy to Cloud Run

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: pitchperfect-lewagon
  SERVICE_NAME: pitch-perfect-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: 'Submit to Cloud Build'
      run: |
        gcloud builds submit --config cloudbuild.yaml